#/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1

/g4simple/setRandomSeed true

/g4simple/setReferencePhysList Shielding
#/physics_engine/tailor/MuonNuclear on

##Geometry File to run simulation with
/g4simple/setDetectorGDML ./geometries/gscanner_241Am.gdml

##Specify output file
/g4simple/setOutputFormat hdf5
#/analysis/setFileName ./raw_out/test_e100000.hdf5
#/analysis/setFileName ./raw_out/test_241Am100000.hdf5
#/analysis/setFileName ./raw_out/test2_e100000.hdf5

#/analysis/setFileName ./raw_out/test_sebColl_241Am100000.hdf5
#/analysis/setFileName ./raw_out/test_sebColl_241Am500000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_241Am500000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_noPhys_241Am500000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_noPhys_241Am700000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_inGe_241Am700000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_30mm_241Am700000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_35mm_241Am700000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_40mm_241Am700000.hdf5
#/analysis/setFileName ./raw_out/test_noColl_45mm_241Am700000.hdf5
/analysis/setFileName ./raw_out/test_noColl_physVol_45mm_241Am700000.hdf5

#/analysis/setFileName ./raw_out/test_sebColl_e100000.hdf5


#/analysis/setFileName ./raw_out/test3_e100000.hdf5
#/analysis/setFileName ./raw_out/test4_e100000.hdf5
#/analysis/setFileName ./raw_out/test5_e100000.hdf5
#/analysis/setFileName ./raw_out/test6_e100000.hdf5
#/analysis/setFileName ./raw_out/test7_e100000.hdf5
#/analysis/setFileName ./raw_out/test8_e100000.hdf5
#/analysis/setFileName ./raw_out/test9_e100000.hdf5
#/analysis/setFileName ./raw_out/test10_e100000.hdf5
#/analysis/setFileName ./raw_out/test11_e100000.hdf5
#/analysis/setFileName ./raw_out/test12_e100000.hdf5
#/analysis/setFileName ./raw_out/test13_e100000.hdf5


##Set Volume ID's for Geometry Volumes (volume.in.geometry.file_PV volID)
/g4simple/setVolID OPPI1_Detector_PV 1
#/g4simple/setVolID Source_Disk_PV 2
#/g4simple/setVolID vacuum_volume_PV 3

##to track all steps, including steps for which Edep=0
#/g4simple/recordAllSteps

##initialize the run
/run/initialize
#/process/em/fluo true

/g4simple/listPhysVols

##Set Source Specifications; particle type, ion specifications (proton number, nucleon number, ionic charge, excitation energy in keV),  geometrical specifications (3 lines, comment these out to make point source), position of source, what volume in geometry file to confine the source to (will take overlap of source geometry and volume in geometry file to make new source geometry, comment this out to not confine source to any volume in geometry file).
/gps/particle ion
/gps/ion 95 241 0 0
/grdm/nucleusLimits 241 241 95 95
/gps/energy 0 MeV

#/gps/particle e-
#/gps/ene/mono 5 MeV
#/gps/ang/type iso
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 40 mm
#/gps/pos/halfy 40 mm
#/gps/direction 0 0 -1

#/gps/pos/type Point
/gps/pos/shape Sphere
/gps/pos/radius 15.0 mm
/gps/pos/centre 0 0 45 mm
#/gps/pos/centre 0 0 45.4 mm #detector height/2+ 16 mm above detector + collimator bottom + collimator middle + source disk height/2
/gps/pos/confine Source_Disk_PV

##set number of runs
/run/beamOn 700000
