#/run/verbose 1
#/event/verbose 1
/tracking/verbose 1

/g4simple/setRandomSeed true

/g4simple/setReferencePhysList Shielding
#/physics_engine/tailor/MuonNuclear on

##Geometry File to run simulation with
/g4simple/setDetectorGDML ./geometries/new_gscanner_241Am.gdml

##Specify output file
/g4simple/setOutputFormat hdf5
/analysis/setFileName ./alpha/raw_out/test.hdf5

##Set Volume ID's for Geometry Volumes (volume.in.geometry.file_PV volID)
#/g4simple/setVolID Top_Hat_PV 1
/g4simple/setVolID PPM_Detector_PV 1
/g4simple/setVolID source_confinement_PV 2
#/g4simple/setVolID Am_Collimator_sebastian_PV 3
#/g4simple/setVolID vacuum_volume_PV 4

##to track all steps, including steps for which Edep=0
#/g4simple/recordAllSteps

##initialize the run
/run/initialize
#/process/em/fluo true

/g4simple/listPhysVols

##Set Source Specifications; particle type, ion specifications (proton number, nucleon number, ionic charge, excitation energy in keV),  geometrical specifications (3 lines, comment these out to make point source), position of source, what volume in geometry file to confine the source to (will take overlap of source geometry and volume in geometry file to make new source geometry, comment this out to not confine source to any volume in geometry file).

/gps/particle ion
/gps/ion 95 241 0 0
/grdm/nucleusLimits 241 241 95 95
/gps/energy 0 MeV


/gps/ang/type iso
/gps/pos/centre 0 -1.906 2.935 mm
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/radius 3.5 mm
/gps/pos/confine source_confinement_PV


#/gps/particle gamma
#/gps/energy 60. keV
#/gps/pos/type Volume
#/gps/pos/shape Para
#/gps/pos/halfx 3.5 mm
#/gps/pos/halfy 3.5 mm
#/gps/pos/halfz 0.0005 mm
#/gps/direction 0 0 -1

#/gps/pos/rot1 1 0.83876 0
#/gps/pos/rot2 1 0 0.5446

#/gps/particle gamma
#/gps/energy 60. keV
#/gps/direction 0 0 -1
#/gps/pos/centre 0 0 3.5 mm
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 0.83867 0.5446




##set number of runs
/run/beamOn 10
