services:
    # a rabbit broker
    rabbit_broker:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
    # a psql database
    psql_db:
        build: postgresql
        volumes:
          - db:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          - POSTGRES_PASSWORD=postgres108
    metabase:
        image: metabase/metabase:v0.31.2
        volumes:
          - mb:/metabase-data
        ports:
          - 3000:3000
        environment:
          - MB_DB_FILE=/metabase-data/metabase.db
    # dragonfly service
    dragonfly:
        build: dragonfly
        command: supervisord
        depends_on:
          - rabbit_broker
          - psql_db
        ## These volumes can be added for easier development
        ## to use them, you must connect and execute `python setup.py develop`
        ## in each to build the requisite python objects (one time only)
        volumes:
            - ./project8_authentications.json:/root/.project8_authentications.json
            # the following mount is the dragonfly config files
            - ./dragonfly/config:/config
          #  - ./dragonfly/dripline:/code/dripline
          #  - ./dragonfly/dragonfly:/code/dragonfly
        ports:
          - 9001:9001
        restart: on-failure
    slowdash:
        image: slowproj/slowdash
        ports:
          - "18881:18881"
        volumes:
          - ./authentications.json:/project/authentications.json
          - ./slowdash.d:/project
        environment:
          - DRIPLINE_DB_URL=postgresql://cage_db_user:legend@psql_db:5432/cage_sc_db
          - JUPYTER_URL=http://localhost:8888
          - JUPYTER_TOKEN=SlowJupyter
          - JUPYTER_INTERNAL_URL=http://notebook:8888
          - SLOWDASH_INTERNAL_URL=http://slowdash:18881
          
    notebook:
        image: slowproj/slowpy-notebook
        command:
          - start-notebook.sh
          - --NotebookApp.token=SlowJupyter
        ports:
          - 8888:8888

volumes:
    db:
      #external: true
      #name: 'cage_db'
    mb:
